server:
  port: 80

spring:
  application:
    name: orchard-service
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false
  thymeleaf:
    cache: false
    check-template-location: true
    enabled: true

  datasource:
    driver-class-name: org.h2.Driver