server:
  port: 80

spring:
  application:
    name: orchard-service
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
        hibernate:
          format_sql: true
  thymeleaf:
    cache: false
    check-template-location: true
    enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/orchard
    username: 'jhlim'
    password: '@jhlim0205'
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  accessToken-validity-in-seconds: 86400
  refreshToken-validity-in-seconds: 86400

logging:
  level:
    org.hibernate.SQL: debug