server:
  port: 8080

spring:

  application:
    name: orchard-service
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
        hibernate:
          format_sql: true
  thymeleaf:
    cache: false
    check-template-location: true
    enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/orchard
    username: 'jhlim'
    password: '@jhlim0205'
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  accessToken-validity-in-seconds: 3600
  refreshToken-validity-in-seconds: 1209600

nice:
  api: https://sandbox-api.nicepay.co.kr
  return-host: http://localhost:8080
  client-id: S2_73cd46ca986a446fa9be3aa0debd4e1e
  secret-key: 695f3943656941bfb185f6879638d81f

ncp:
  from: 01050991560
  serviceId: ncp:sms:kr:331715689787:orchard-sms
  accessKey: pukYZhVuMgVcdIOSR5xo
  secretKey: HhbJNJzoP9ayCAingEEP9FAu444um0ZlKjVYBCcv
  smsApiUrl: https://sens.apigw.ntruss.com

cookie:
  secure: false
  domain: localhost

logging:
  level:
    org.hibernate.SQL: debug